/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Session */
        get: operations["read_session_api_auth_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics/web-vitals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reserve Web Vitals */
        post: operations["reserve_web_vitals_api_metrics_web_vitals_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Settings */
        get: operations["read_settings_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Settings */
        patch: operations["patch_settings_api_settings_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthLoginRequest */
        AuthLoginRequest: {
            /** Mfa Code */
            mfa_code?: string | null;
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** AuthSessionResponse */
        AuthSessionResponse: {
            /** Authenticated */
            authenticated: boolean;
            /** Csrf Token */
            csrf_token?: string | null;
            settings?: components["schemas"]["SettingsResponse"] | null;
            tenant?: components["schemas"]["SessionTenantResponse"] | null;
            user?: components["schemas"]["SessionUserResponse"] | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Params */
            params?: {
                [key: string]: components["schemas"]["JsonPrimitive"];
            };
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            detail: components["schemas"]["ErrorDetail"];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        JsonPrimitive: string | number | boolean | null;
        /** ReadinessCheck */
        ReadinessCheck: {
            /**
             * Name
             * @enum {string}
             */
            name: "database" | "sse_broker";
            /** Ok */
            ok: boolean;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Checks */
            checks: components["schemas"]["ReadinessCheck"][];
            /**
             * Status
             * @enum {string}
             */
            status: "ready" | "not_ready";
        };
        /** SessionTenantResponse */
        SessionTenantResponse: {
            /** Cohort Id */
            cohort_id?: string | null;
            /** Course Id */
            course_id: string;
            /** Org Id */
            org_id: string;
            /** Role */
            role: string;
        };
        /** SessionUserResponse */
        SessionUserResponse: {
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Id */
            id: string;
        };
        /** SettingsPatchRequest */
        SettingsPatchRequest: {
            /** Locale */
            locale?: string | null;
            /** Selected Course Id */
            selected_course_id?: string | null;
            /** Theme */
            theme?: string | null;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Locale */
            locale: string;
            /** Selected Course Id */
            selected_course_id?: string | null;
            /** Theme */
            theme: string;
        };
        /** WebVitalsReservedResponse */
        WebVitalsReservedResponse: {
            /**
             * Code
             * @constant
             */
            code: "metrics.web_vitals.reserved";
            /**
             * Status
             * @constant
             */
            status: "reserved";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Request correlation identifier. */
                    "X-Request-ID"?: string;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    /** @description Request correlation identifier. */
                    "X-Request-ID"?: string;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    /** @description Request correlation identifier. */
                    "X-Request-ID"?: string;
                };
                content?: never;
            };
        };
    };
    read_session_api_auth_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Request correlation identifier. */
                    "X-Request-ID"?: string;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Request correlation identifier. */
                    "X-Request-ID"?: string;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    reserve_web_vitals_api_metrics_web_vitals_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    /** @description Request correlation identifier. */
                    "X-Request-ID"?: string;
                };
                content: {
                    "application/json": components["schemas"]["WebVitalsReservedResponse"];
                };
            };
        };
    };
    ready_api_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Request correlation identifier. */
                    "X-Request-ID"?: string;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    /** @description Request correlation identifier. */
                    "X-Request-ID"?: string;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    read_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Request correlation identifier. */
                    "X-Request-ID"?: string;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    patch_settings_api_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    /** @description Request correlation identifier. */
                    "X-Request-ID"?: string;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    /** @description Request correlation identifier. */
                    "X-Request-ID"?: string;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
