"""Baseline Postgres schema.

Ports the tables SQLite migrations 001-024 built up. Autogenerated from
``sophia.infra.schema`` and then hand-reviewed: the create order respects the
foreign keys, the drop order reverses it, and every check constraint carries an
explicit name so a later revision can reference it.

Revision ID: 0001_baseline
Revises:
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_baseline"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    op.create_table(
        "active_timers",
        sa.Column("deadline_id", sa.Text(), nullable=False),
        sa.Column("started_at", sa.Text(), nullable=False),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column("course_id", sa.Text(), server_default="default", nullable=False),
        sa.PrimaryKeyConstraint("deadline_id", name=op.f("pk_active_timers")),
    )
    op.create_table(
        "book_cache",
        sa.Column("isbn", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("authors", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.Text(), nullable=True),
        sa.Column("last_searched", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column("course_id", sa.Text(), server_default="default", nullable=False),
        sa.PrimaryKeyConstraint("isbn", name=op.f("pk_book_cache")),
    )
    op.create_table(
        "confidence_ratings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("predicted", sa.Float(), nullable=False),
        sa.Column("actual", sa.Float(), nullable=True),
        sa.Column(
            "rated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("actual_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.CheckConstraint(
            "actual IS NULL OR actual BETWEEN 0.0 AND 1.0",
            name=op.f("ck_confidence_ratings_actual_ratio"),
        ),
        sa.CheckConstraint(
            "predicted BETWEEN 0.0 AND 1.0", name=op.f("ck_confidence_ratings_predicted_ratio")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_confidence_ratings")),
    )
    op.create_index(
        "idx_confidence_ratings_course", "confidence_ratings", ["course_id"], unique=False
    )
    op.create_index(
        "idx_confidence_ratings_topic", "confidence_ratings", ["course_id", "topic"], unique=False
    )
    op.create_table(
        "content_provenance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_kind", sa.Text(), nullable=False),
        sa.Column("content_id", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("content_origin", sa.Text(), server_default="tuwel", nullable=False),
        sa.Column("generated_by", sa.Text(), nullable=False),
        sa.Column("generator_ref", sa.Text(), nullable=True),
        sa.Column(
            "generated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("verified_by", sa.Text(), nullable=True),
        sa.Column("verified_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_provenance")),
        sa.UniqueConstraint(
            "content_kind", "content_id", name="uq_content_provenance_content_kind"
        ),
    )
    op.create_index(
        "idx_content_provenance_scope",
        "content_provenance",
        ["course_id", "content_kind"],
        unique=False,
    )
    op.create_table(
        "content_translations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("content_kind", sa.Text(), nullable=False),
        sa.Column("content_id", sa.Text(), nullable=False),
        sa.Column("language", sa.Text(), nullable=False),
        sa.Column("translated_text", sa.Text(), server_default="", nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column(
            "translated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_translations")),
        sa.UniqueConstraint(
            "content_kind", "content_id", "language", name="uq_content_translations_content_kind"
        ),
    )
    op.create_table(
        "course_materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("mimetype", sa.Text(), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("pdf_text", sa.Text(), nullable=True),
        sa.Column("chunk_count", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.Text(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_course_materials")),
    )
    op.create_index(
        "uq_course_materials_url", "course_materials", ["course_id", "url"], unique=True
    )
    op.create_table(
        "deadline_cache",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("course_name", sa.Text(), server_default="", nullable=False),
        sa.Column("deadline_type", sa.Text(), nullable=False),
        sa.Column("due_at", sa.Text(), nullable=False),
        sa.Column("grade_weight", sa.Float(), nullable=True),
        sa.Column("submission_status", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("extra", sa.Text(), server_default="{}", nullable=True),
        sa.Column(
            "synced_at", sa.Text(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deadline_cache")),
    )
    op.create_index("idx_deadline_cache_course", "deadline_cache", ["course_id"], unique=False)
    op.create_index("idx_deadline_cache_due", "deadline_cache", ["due_at"], unique=False)
    op.create_table(
        "deadline_reflections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deadline_id", sa.Text(), nullable=False),
        sa.Column("predicted_hours", sa.Float(), nullable=True),
        sa.Column("actual_hours", sa.Float(), nullable=True),
        sa.Column("reflection_text", sa.Text(), nullable=True),
        sa.Column(
            "reflected_at", sa.Text(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column("course_id", sa.Text(), server_default="default", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deadline_reflections")),
    )
    op.create_table(
        "discovered_references",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("authors", sa.Text(), server_default="[]", nullable=False),
        sa.Column("isbn", sa.Text(), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("course_name", sa.Text(), server_default="", nullable=False),
        sa.Column("confidence", sa.Float(), server_default=sa.text("1.0"), nullable=False),
        sa.Column(
            "discovered_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovered_references")),
        sa.UniqueConstraint("title", "course_id", "source", name="uq_discovered_references_title"),
    )
    op.create_index(
        "idx_discovered_refs_course", "discovered_references", ["course_id"], unique=False
    )
    op.create_index(
        "idx_discovered_refs_course_name", "discovered_references", ["course_name"], unique=False
    )
    op.create_index("idx_discovered_refs_isbn", "discovered_references", ["isbn"], unique=False)
    op.create_table(
        "downloads",
        sa.Column("md5", sa.Text(), nullable=False),
        sa.Column("isbn", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("authors", sa.Text(), nullable=True),
        sa.Column("format", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("is_open_access", sa.Boolean(), server_default=sa.text("FALSE"), nullable=True),
        sa.Column("retail_price", sa.Float(), nullable=True),
        sa.Column(
            "downloaded_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column("course_id", sa.Text(), server_default="default", nullable=False),
        sa.PrimaryKeyConstraint("md5", name=op.f("pk_downloads")),
    )
    op.create_table(
        "effort_estimates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deadline_id", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("predicted_hours", sa.Float(), nullable=False),
        sa.Column("breakdown", sa.Text(), nullable=True),
        sa.Column("implementation_intention", sa.Text(), nullable=True),
        sa.Column("scaffold_level", sa.Text(), server_default="full", nullable=False),
        sa.Column(
            "estimated_at", sa.Text(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.CheckConstraint(
            "predicted_hours > 0", name=op.f("ck_effort_estimates_predicted_hours_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_effort_estimates")),
    )
    op.create_index("idx_effort_estimates_course", "effort_estimates", ["course_id"], unique=False)
    op.create_index(
        "idx_effort_estimates_deadline", "effort_estimates", ["deadline_id"], unique=False
    )
    op.create_table(
        "generated_questions",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("prompt", sa.Text(), server_default="", nullable=False),
        sa.Column("difficulty", sa.Text(), nullable=False),
        sa.Column("content_language", sa.Text(), server_default="de", nullable=False),
        sa.Column("options", sa.Text(), server_default="[]", nullable=False),
        sa.Column("segments", sa.Text(), server_default="[]", nullable=False),
        sa.Column("elaboration_policy", sa.Text(), nullable=True),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_questions")),
    )
    op.create_index(
        "idx_generated_questions_scope", "generated_questions", ["course_id", "topic"], unique=False
    )
    op.create_table(
        "learning_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("occurred_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("session_id", sa.Integer(), nullable=True),
        sa.Column("question_id", sa.Text(), nullable=True),
        sa.Column("payload", sa.Text(), server_default="{}", nullable=False),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_events")),
        sa.UniqueConstraint("event_id", name=op.f("uq_learning_events_event_id")),
    )
    op.create_index(
        "idx_learning_events_retention", "learning_events", ["received_at"], unique=False
    )
    op.create_index(
        "idx_learning_events_trace",
        "learning_events",
        ["course_id", "question_id", "user_id", "event_type"],
        unique=False,
    )
    op.create_table(
        "learning_path_settings",
        sa.Column("course_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("exam_language", sa.Text(), server_default="de", nullable=False),
        sa.Column("content_origin", sa.Text(), server_default="tuwel", nullable=False),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("course_id", name=op.f("pk_learning_path_settings")),
    )
    op.create_table(
        "lecture_downloads",
        sa.Column("episode_id", sa.Text(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("series_id", sa.Text(), server_default="", nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("track_url", sa.Text(), nullable=False),
        sa.Column("track_mimetype", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("status", sa.Text(), server_default="queued", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("skip_reason", sa.Text(), nullable=True),
        sa.Column("lecture_number", sa.Integer(), nullable=True),
        sa.Column("missed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column("course_id", sa.Text(), server_default="default", nullable=False),
        sa.PrimaryKeyConstraint("episode_id", name=op.f("pk_lecture_downloads")),
    )
    op.create_index(
        "idx_lecture_downloads_module", "lecture_downloads", ["module_id"], unique=False
    )
    op.create_index("idx_lecture_downloads_status", "lecture_downloads", ["status"], unique=False)
    op.create_table(
        "lecture_modules",
        sa.Column("module_id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("course_name", sa.Text(), server_default="", nullable=False),
        sa.Column("course_shortname", sa.Text(), server_default="", nullable=False),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column("course_id", sa.Text(), server_default="default", nullable=False),
        sa.PrimaryKeyConstraint("module_id", name=op.f("pk_lecture_modules")),
    )
    op.create_table(
        "metacognition_log",
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column("item_id", sa.Text(), nullable=False),
        sa.Column("predicted", sa.Float(), nullable=False),
        sa.Column("actual", sa.Float(), nullable=True),
        sa.Column(
            "predicted_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("actual_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column("course_id", sa.Text(), server_default="default", nullable=False),
        sa.PrimaryKeyConstraint("domain", "item_id", name=op.f("pk_metacognition_log")),
    )
    op.create_table(
        "review_schedule",
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("interval_index", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_reviewed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("next_review_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("score_at_last_review", sa.Float(), nullable=True),
        sa.Column("difficulty", sa.Float(), server_default=sa.text("0.3"), nullable=True),
        sa.Column("stability", sa.Float(), server_default=sa.text("1.0"), nullable=True),
        sa.Column("review_count", sa.Integer(), server_default=sa.text("0"), nullable=True),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.PrimaryKeyConstraint("topic", "course_id", name=op.f("pk_review_schedule")),
    )
    op.create_index("idx_review_schedule_due", "review_schedule", ["next_review_at"], unique=False)
    op.create_table(
        "scheduled_jobs",
        sa.Column("job_id", sa.Text(), nullable=False),
        sa.Column("command", sa.Text(), nullable=False),
        sa.Column("scheduled_for", sa.Text(), nullable=False),
        sa.Column("created_at", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("description", sa.Text(), server_default="", nullable=False),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column("course_id", sa.Text(), server_default="default", nullable=False),
        sa.PrimaryKeyConstraint("job_id", name=op.f("pk_scheduled_jobs")),
    )
    op.create_table(
        "student_flashcards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("front", sa.Text(), nullable=False),
        sa.Column("back", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), server_default="study", nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.CheckConstraint(
            "source IN ('study', 'lecture', 'manual')",
            name=op.f("ck_student_flashcards_source_allowed"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_student_flashcards")),
    )
    op.create_index("idx_flashcards_course", "student_flashcards", ["course_id"], unique=False)
    op.create_index(
        "idx_flashcards_topic", "student_flashcards", ["course_id", "topic"], unique=False
    )
    op.create_table(
        "study_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("pre_test_score", sa.Float(), nullable=True),
        sa.Column("post_test_score", sa.Float(), nullable=True),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.CheckConstraint(
            "post_test_score IS NULL OR post_test_score BETWEEN 0.0 AND 1.0",
            name=op.f("ck_study_sessions_post_test_ratio"),
        ),
        sa.CheckConstraint(
            "pre_test_score IS NULL OR pre_test_score BETWEEN 0.0 AND 1.0",
            name=op.f("ck_study_sessions_pre_test_ratio"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_study_sessions")),
    )
    op.create_index("idx_study_sessions_course", "study_sessions", ["course_id"], unique=False)
    op.create_index(
        "idx_study_sessions_topic", "study_sessions", ["course_id", "topic"], unique=False
    )
    op.create_table(
        "time_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("deadline_id", sa.Text(), nullable=False),
        sa.Column("hours", sa.Float(), nullable=False),
        sa.Column("source", sa.Text(), server_default="manual", nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "recorded_at", sa.Text(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column("course_id", sa.Text(), server_default="default", nullable=False),
        sa.CheckConstraint("hours > 0", name=op.f("ck_time_entries_hours_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_time_entries")),
    )
    op.create_index("idx_time_entries_deadline", "time_entries", ["deadline_id"], unique=False)
    op.create_table(
        "topic_lecture_links",
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Text(), nullable=False),
        sa.Column("episode_id", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), server_default=sa.text("0.0"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.PrimaryKeyConstraint(
            "topic", "course_id", "chunk_id", name=op.f("pk_topic_lecture_links")
        ),
    )
    op.create_index(
        "idx_topic_lecture_links_course", "topic_lecture_links", ["course_id"], unique=False
    )
    op.create_index(
        "idx_topic_lecture_links_episode", "topic_lecture_links", ["episode_id"], unique=False
    )
    op.create_table(
        "topic_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("topic", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.Text(), server_default="lecture", nullable=False),
        sa.Column("frequency", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.CheckConstraint(
            "source IN ('lecture', 'quiz', 'manual')", name=op.f("ck_topic_mappings_source_allowed")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_mappings")),
        sa.UniqueConstraint("topic", "course_id", "source", name="uq_topic_mappings_topic"),
    )
    op.create_index("idx_topic_mappings_course", "topic_mappings", ["course_id"], unique=False)
    op.create_table(
        "topic_reconciliations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("manual_topic", sa.Text(), nullable=False),
        sa.Column("moodle_topic", sa.Text(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column(
            "reconciled_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_topic_reconciliations")),
        sa.UniqueConstraint(
            "manual_topic", "course_id", name="uq_topic_reconciliations_manual_topic"
        ),
    )
    op.create_table(
        "card_review_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("flashcard_id", sa.Integer(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column(
            "reviewed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column("course_id", sa.Text(), server_default="default", nullable=False),
        sa.ForeignKeyConstraint(
            ["flashcard_id"],
            ["student_flashcards.id"],
            name=op.f("fk_card_review_attempts_flashcard_id_student_flashcards"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_review_attempts")),
    )
    op.create_index(
        "idx_card_reviews_flashcard", "card_review_attempts", ["flashcard_id"], unique=False
    )
    op.create_table(
        "content_source_spans",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provenance_id", sa.Integer(), nullable=False),
        sa.Column("content_item_id", sa.Text(), nullable=False),
        sa.Column("start_char", sa.Integer(), nullable=True),
        sa.Column("end_char", sa.Integer(), nullable=True),
        sa.Column("start_ms", sa.Integer(), nullable=True),
        sa.Column("end_ms", sa.Integer(), nullable=True),
        sa.Column("excerpt", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["provenance_id"],
            ["content_provenance.id"],
            name=op.f("fk_content_source_spans_provenance_id_content_provenance"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_content_source_spans")),
    )
    op.create_index(
        "idx_content_source_spans_provenance",
        "content_source_spans",
        ["provenance_id"],
        unique=False,
    )
    op.create_table(
        "question_attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("answer_text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=True),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column(
            "submitted_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["generated_questions.id"],
            name=op.f("fk_question_attempts_question_id_generated_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_attempts")),
    )
    op.create_index(
        "idx_question_attempts_scope",
        "question_attempts",
        ["course_id", "question_id", "user_id"],
        unique=False,
    )
    op.create_table(
        "self_explanations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("flashcard_id", sa.Integer(), nullable=False),
        sa.Column("student_explanation", sa.Text(), nullable=False),
        sa.Column("scaffold_level", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column("course_id", sa.Text(), server_default="default", nullable=False),
        sa.CheckConstraint(
            "scaffold_level BETWEEN 0 AND 3", name=op.f("ck_self_explanations_scaffold_level_range")
        ),
        sa.ForeignKeyConstraint(
            ["flashcard_id"],
            ["student_flashcards.id"],
            name=op.f("fk_self_explanations_flashcard_id_student_flashcards"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_self_explanations")),
    )
    op.create_index(
        "idx_self_explanations_flashcard", "self_explanations", ["flashcard_id"], unique=False
    )
    op.create_table(
        "transcriptions",
        sa.Column("episode_id", sa.Text(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.Text(), server_default="de", nullable=False),
        sa.Column("duration_s", sa.Float(), nullable=True),
        sa.Column("segment_count", sa.Integer(), nullable=True),
        sa.Column("srt_path", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("completed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column("course_id", sa.Text(), server_default="default", nullable=False),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["lecture_downloads.episode_id"],
            name=op.f("fk_transcriptions_episode_id_lecture_downloads"),
        ),
        sa.PrimaryKeyConstraint("episode_id", name=op.f("pk_transcriptions")),
    )
    op.create_index("idx_transcriptions_status", "transcriptions", ["status"], unique=False)
    op.create_table(
        "knowledge_index",
        sa.Column("episode_id", sa.Text(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("chunk_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("status", sa.Text(), server_default="pending", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("indexed_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=True,
        ),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column("course_id", sa.Text(), server_default="default", nullable=False),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["transcriptions.episode_id"],
            name=op.f("fk_knowledge_index_episode_id_transcriptions"),
        ),
        sa.PrimaryKeyConstraint("episode_id", name=op.f("pk_knowledge_index")),
    )
    op.create_index("idx_knowledge_index_status", "knowledge_index", ["status"], unique=False)
    op.create_table(
        "transcript_segments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("episode_id", sa.Text(), nullable=False),
        sa.Column("segment_index", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("org_id", sa.Text(), server_default="default", nullable=False),
        sa.Column("course_id", sa.Text(), server_default="default", nullable=False),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["transcriptions.episode_id"],
            name=op.f("fk_transcript_segments_episode_id_transcriptions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcript_segments")),
    )
    op.create_index(
        "idx_transcript_segments_episode", "transcript_segments", ["episode_id"], unique=False
    )


def downgrade() -> None:
    op.drop_index("idx_transcript_segments_episode", table_name="transcript_segments")
    op.drop_table("transcript_segments")
    op.drop_index("idx_knowledge_index_status", table_name="knowledge_index")
    op.drop_table("knowledge_index")
    op.drop_index("idx_transcriptions_status", table_name="transcriptions")
    op.drop_table("transcriptions")
    op.drop_index("idx_self_explanations_flashcard", table_name="self_explanations")
    op.drop_table("self_explanations")
    op.drop_index("idx_question_attempts_scope", table_name="question_attempts")
    op.drop_table("question_attempts")
    op.drop_index("idx_content_source_spans_provenance", table_name="content_source_spans")
    op.drop_table("content_source_spans")
    op.drop_index("idx_card_reviews_flashcard", table_name="card_review_attempts")
    op.drop_table("card_review_attempts")
    op.drop_table("topic_reconciliations")
    op.drop_index("idx_topic_mappings_course", table_name="topic_mappings")
    op.drop_table("topic_mappings")
    op.drop_index("idx_topic_lecture_links_episode", table_name="topic_lecture_links")
    op.drop_index("idx_topic_lecture_links_course", table_name="topic_lecture_links")
    op.drop_table("topic_lecture_links")
    op.drop_index("idx_time_entries_deadline", table_name="time_entries")
    op.drop_table("time_entries")
    op.drop_index("idx_study_sessions_topic", table_name="study_sessions")
    op.drop_index("idx_study_sessions_course", table_name="study_sessions")
    op.drop_table("study_sessions")
    op.drop_index("idx_flashcards_topic", table_name="student_flashcards")
    op.drop_index("idx_flashcards_course", table_name="student_flashcards")
    op.drop_table("student_flashcards")
    op.drop_table("scheduled_jobs")
    op.drop_index("idx_review_schedule_due", table_name="review_schedule")
    op.drop_table("review_schedule")
    op.drop_table("metacognition_log")
    op.drop_table("lecture_modules")
    op.drop_index("idx_lecture_downloads_status", table_name="lecture_downloads")
    op.drop_index("idx_lecture_downloads_module", table_name="lecture_downloads")
    op.drop_table("lecture_downloads")
    op.drop_table("learning_path_settings")
    op.drop_index("idx_learning_events_trace", table_name="learning_events")
    op.drop_index("idx_learning_events_retention", table_name="learning_events")
    op.drop_table("learning_events")
    op.drop_index("idx_generated_questions_scope", table_name="generated_questions")
    op.drop_table("generated_questions")
    op.drop_index("idx_effort_estimates_deadline", table_name="effort_estimates")
    op.drop_index("idx_effort_estimates_course", table_name="effort_estimates")
    op.drop_table("effort_estimates")
    op.drop_table("downloads")
    op.drop_index("idx_discovered_refs_isbn", table_name="discovered_references")
    op.drop_index("idx_discovered_refs_course_name", table_name="discovered_references")
    op.drop_index("idx_discovered_refs_course", table_name="discovered_references")
    op.drop_table("discovered_references")
    op.drop_table("deadline_reflections")
    op.drop_index("idx_deadline_cache_due", table_name="deadline_cache")
    op.drop_index("idx_deadline_cache_course", table_name="deadline_cache")
    op.drop_table("deadline_cache")
    op.drop_index("uq_course_materials_url", table_name="course_materials")
    op.drop_table("course_materials")
    op.drop_table("content_translations")
    op.drop_index("idx_content_provenance_scope", table_name="content_provenance")
    op.drop_table("content_provenance")
    op.drop_index("idx_confidence_ratings_topic", table_name="confidence_ratings")
    op.drop_index("idx_confidence_ratings_course", table_name="confidence_ratings")
    op.drop_table("confidence_ratings")
    op.drop_table("book_cache")
    op.drop_table("active_timers")
