"""Tests for the captions adapter — WebVTT parsing, track choice, fetching."""

from __future__ import annotations

import httpx
import pytest
import respx

from sophia.adapters.captions import (
    HttpCaptionFetcher,
    parse_vtt,
    select_caption_track,
)
from sophia.domain.errors import CaptionError
from sophia.domain.models import LectureCaption
from sophia.domain.ports import CaptionFetcher

# The shape cdn.video.tuwien.ac.at serves: a trailing space after each timing
# line and a leading space on each text line, as sampled on 2026-10-09.
TUWIEN_VTT = (
    "WEBVTT\n"
    "\n"
    "00:00:02.910 --> 00:00:06.402 \n"
    " So, willkommen zur letzten Vorlesung Einführung in die Programmierung 1.\n"
    "\n"
    "00:00:08.342 --> 00:00:14.402 \n"
    " Ich wollte heute das zeigen, was ich schon angekündigt habe.\n"
    "\n"
    "01:25:47.442 --> 01:25:50.422 \n"
    " Und dann viel Erfolg in den nächsten Semester.\n"
)


def _caption(lang: str, fmt: str = "vtt") -> LectureCaption:
    return LectureCaption(lang=lang, url=f"https://cdn.example/{lang}.{fmt}", format=fmt)


class TestParseVtt:
    def test_keeps_cue_times_and_text(self) -> None:
        segments = parse_vtt(TUWIEN_VTT)

        assert len(segments) == 3
        assert segments[0].start == pytest.approx(2.91)
        assert segments[0].end == pytest.approx(6.402)
        assert segments[0].text.startswith("So, willkommen zur letzten Vorlesung")
        assert segments[2].start == pytest.approx(1 * 3600 + 25 * 60 + 47.442)

    def test_handles_bom_header_text_ids_settings_notes_and_tags(self) -> None:
        document = (
            "﻿WEBVTT - generated by somebody\n"
            "\n"
            "NOTE this block is a comment\n"
            "and spans two lines\n"
            "\n"
            "STYLE\n"
            "::cue { color: white }\n"
            "\n"
            "intro\n"
            "00:01.000 --> 00:03.500 align:start position:10%\n"
            "<v Lecturer>Erste <i>Zeile</i>\n"
            "zweite Zeile\n"
            "\n"
            "00:04.000 --> 00:05.000\n"
            "\n"
        )

        segments = parse_vtt(document)

        assert len(segments) == 1
        assert segments[0].start == pytest.approx(1.0)
        assert segments[0].end == pytest.approx(3.5)
        assert segments[0].text == "Erste Zeile zweite Zeile"

    def test_empty_document_has_no_segments(self) -> None:
        assert parse_vtt("WEBVTT\n") == []

    def test_rejects_a_document_that_is_not_vtt(self) -> None:
        with pytest.raises(CaptionError, match="not a WebVTT"):
            parse_vtt("<html>Not found</html>")

    def test_rejects_a_malformed_timing_line(self) -> None:
        with pytest.raises(CaptionError, match="malformed cue timing"):
            parse_vtt("WEBVTT\n\n00:00:01 --> soon\nText\n")


class TestSelectCaptionTrack:
    def test_prefers_the_course_language(self) -> None:
        tracks = [_caption("de"), _caption("en")]

        assert select_caption_track(tracks, "en") is tracks[1]
        assert select_caption_track(tracks, "de") is tracks[0]

    def test_falls_back_to_german_when_the_course_language_is_missing(self) -> None:
        tracks = [_caption("en"), _caption("de")]

        assert select_caption_track(tracks, "fr") is tracks[1]

    def test_regional_tags_match_their_base_language(self) -> None:
        tracks = [_caption("de-AT")]

        assert select_caption_track(tracks, "de") is tracks[0]

    def test_returns_none_when_neither_language_has_a_track(self) -> None:
        assert select_caption_track([_caption("en")], "fr") is None
        assert select_caption_track([], "de") is None

    def test_ignores_tracks_that_are_not_vtt(self) -> None:
        assert select_caption_track([_caption("de", fmt="dfxp")], "de") is None


class TestHttpCaptionFetcher:
    def test_conforms_to_protocol(self) -> None:
        fetcher = HttpCaptionFetcher(httpx.AsyncClient())
        assert callable(getattr(fetcher, "fetch_captions", None))
        assert isinstance(CaptionFetcher, type)

    @respx.mock
    async def test_returns_the_document_text(self) -> None:
        url = "https://cdn.video.tuwien.ac.at/static/captions.vtt"
        respx.get(url).mock(return_value=httpx.Response(200, text=TUWIEN_VTT))

        async with httpx.AsyncClient() as client:
            text = await HttpCaptionFetcher(client).fetch_captions(url)

        assert text == TUWIEN_VTT

    @respx.mock
    async def test_http_errors_become_caption_errors(self) -> None:
        url = "https://cdn.video.tuwien.ac.at/static/missing.vtt"
        respx.get(url).mock(return_value=httpx.Response(404))

        async with httpx.AsyncClient() as client:
            with pytest.raises(CaptionError, match="HTTP 404"):
                await HttpCaptionFetcher(client).fetch_captions(url)

    @respx.mock
    async def test_transport_errors_become_caption_errors(self) -> None:
        url = "https://cdn.video.tuwien.ac.at/static/unreachable.vtt"
        respx.get(url).mock(side_effect=httpx.ConnectError("refused"))

        async with httpx.AsyncClient() as client:
            with pytest.raises(CaptionError, match="refused"):
                await HttpCaptionFetcher(client).fetch_captions(url)

    @respx.mock
    async def test_oversized_files_are_refused(self) -> None:
        url = "https://cdn.video.tuwien.ac.at/static/huge.vtt"
        respx.get(url).mock(return_value=httpx.Response(200, text="WEBVTT\n" + "x" * 64))

        async with httpx.AsyncClient() as client:
            with pytest.raises(CaptionError, match="exceeds"):
                await HttpCaptionFetcher(client, max_bytes=16).fetch_captions(url)
